version: '3'
services:
  web:
    image: drkimpatrick/tiv-ussd:latest
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
